"""add_is_active_column_to_course_table

Revision ID: 1540b05875eb
Revises: cc57f5680b87
Create Date: 2026-04-02 08:56:43.919148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1540b05875eb'
down_revision: Union[str, Sequence[str], None] = 'cc57f5680b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_active')
    # ### end Alembic commands ###
