"""add_answer_score_to_lesson_questions

Revision ID: 78bcf25fc7fd
Revises: 521e024227a0
Create Date: 2026-04-03 15:51:02.740242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78bcf25fc7fd'
down_revision: Union[str, Sequence[str], None] = '521e024227a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_questions', sa.Column('answer', sa.Text(), nullable=True))
    op.add_column('lesson_questions', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_questions', 'score')
    op.drop_column('lesson_questions', 'answer')
    # ### end Alembic commands ###
