"""Add tags

Revision ID: 7cbe3f493dee
Revises: 78bcf25fc7fd
Create Date: 2026-04-03 16:36:15.593821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbe3f493dee'
down_revision: Union[str, Sequence[str], None] = '78bcf25fc7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('tag', sa.String(), nullable=True))
    op.create_index(op.f('ix_courses_tag'), 'courses', ['tag'], unique=False)
    op.add_column('lessons', sa.Column('tag', sa.String(), nullable=True))
    op.create_index(op.f('ix_lessons_tag'), 'lessons', ['tag'], unique=False)
    op.add_column('modules', sa.Column('tag', sa.String(), nullable=True))
    op.create_index(op.f('ix_modules_tag'), 'modules', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modules_tag'), table_name='modules')
    op.drop_column('modules', 'tag')
    op.drop_index(op.f('ix_lessons_tag'), table_name='lessons')
    op.drop_column('lessons', 'tag')
    op.drop_index(op.f('ix_courses_tag'), table_name='courses')
    op.drop_column('courses', 'tag')
    # ### end Alembic commands ###
